name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-14]

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bazel cache
        uses: actions/cache@v2
        with:
          path: |
            ./.bazel-cache/
          key: ${{ matrix.os }}-bazel-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}-
          restore-keys: |
            ${{ matrix.os }}-bazel-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}-
            ${{ matrix.os }}-bazel-refs/head/main-
            ${{ matrix.os }}-bazel-

      - name: Build all targets
        run: bazel build //...
